name: hotpath-relay

on:
  workflow_run:
    workflows: ["hotpath-benchmark"]
    types:
      - completed

jobs:
  relay:
    uses: pawurb/hotpath-rs/.github/workflows/hotpath-relay.yml@v0.28.5
    permissions:
      actions: read
      id-token: write
      pull-requests: read
    with:
      benchmark: microfetch
      artifact_name: hotpath-report
      report_file: report.json
